title: Piotr Stachyra's Blog
logo: /assets/images/website_logo.png
description: NLP | Signal Processing | Adversarial Artificial Intelligence
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

collections:
  posts:
    output: true
