# Site settings
remote_theme: "mmistakes/minimal-mistakes@4.19.3"

minimal_mistakes_skin: "default"
minimal_mistakes_skin2: "dark"


title: Piotr Stachyra
subtitle: ""
email: pj.stachyra@gmail.com
description: NLP | Signal Processing | Adversarial Artificial Intelligence
words_per_minute: 200
search: true
search_full_content: true

# twitter_username: username
github_username: p-stachyra

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  html_to_native: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _portfolio

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: "Piotr Stachyra"
  avatar: "/assets/images/profile2.jpg"
  bio: "Data scientist | TNO | Msc. Utrecht Univeristy Applied Data Science"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "pj.stachyra@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/p-stachyra"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/piotr-stachyra/"

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true


# category_archive:
#   type: liquid
#   path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development